on: push
name: deploy
jobs:
  deploy:
    name: deploy to cluster
    runs-on: ubuntu-latest
    steps:
      - name: Ckeck out code
        uses: actions/checkout@master
      - name: build and push to docker hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: gilbertodev17/docker-node
          tag_with_ref: true
          tag_with_sha: true
          tags: ${{ github.sha }}
